### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by JiyuanAn** [lorafei/Explainable_GEC#5]
Hello, when I tried to reproduce this creative work according to the instructions, I encountered this error. I hope to get your help and reply. Thanks!
```
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from simpletransformers.ner import NERModel
  File "/data/private/ajy2023/workspace/Explainable_GEC/Explainable_GEC-main/simpletransformers/ner/__init__.py", line 1, in <module>
    from simpletransformers.ner.ner_model import NERModel
  File "/data/private/ajy2023/workspace/Explainable_GEC/Explainable_GEC-main/simpletransformers/ner/ner_model.py", line 119, in <module>
    from simpletransformers.ner.transformer_models.modeling_roberta import RobertaForTokenClassification, SrobertaForSourceTargetTokenClassification
ModuleNotFoundError: No module named 'simpletransformers.ner.transformer_models.modeling_roberta'
```

**Comment by Lj4040** [comment]
解决了吗？

**Comment by Rastapar** [comment]
I have the same error.
